version: "3"
services:
  etl:
    build: .
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - TZ
      - POSTGRES_HOST
      - EMPATIA_ETL_SCHEDULER_HOURS_PARAGUAY
      - KINGFISHER_PARAGUAY_DNCP_REQUEST_TOKEN
